kind: Service
apiVersion: v1
metadata:
  labels:
    node: node2
  name: nodesvc2
spec:
  selector:
    node: node2
  ports:
  - name: discovery
    port: 21000
    targetPort: 21000
  - name: raftport
    port: 50401
    targetPort: 50401
  - name: rpcport
    port: 22000
    targetPort: 22000
  - name: get
    port: 9001
    targetPort: 9001
  type: LoadBalancer